#!/usr/bin/env perl
use warnings;
use strict;
#
# Quick hack to call functions
#

use File::Spec;

# allow the libs to be in the bin dir
use FindBin;
use lib File::Spec->catdir($FindBin::RealBin,"lib");
use lib File::Spec->catdir($ENV{HOME},"s/bin/lib");


use Toggl::Request;

my $result = Toggl::Request->hack_gtimelog2toggl( @ARGV );

print "Result=",$result,"\n";

